
package Apresentacao;

import Modelos.AnalisaDados;
import Modelos.Controle;
import Modelos.Estaticos;
import static Modelos.Estaticos.DadosPessoas;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class frmPrincipal extends javax.swing.JDialog 
{ 
    String resQuestão3="";
    String resQuestão4="";
    String resQuestão5="";
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        Estaticos.Questão3="";
        Estaticos.Questão4="";
        Estaticos.Questão5="";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgQuestao4 = new javax.swing.ButtonGroup();
        btgQuestao5 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tbpPrincipal = new javax.swing.JTabbedPane();
        pnlQuestao1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        btnProximo1 = new javax.swing.JButton();
        lblQuestao1 = new javax.swing.JLabel();
        txfQuestao1 = new javax.swing.JTextField();
        btnTeclado = new javax.swing.JButton();
        pnlQuestao2 = new javax.swing.JPanel();
        lblQuestao2 = new javax.swing.JLabel();
        txfQuestao2 = new javax.swing.JTextField();
        btnProximo2 = new javax.swing.JButton();
        btnAnterior1 = new javax.swing.JButton();
        btnTeclado1 = new javax.swing.JButton();
        pnlQuestao5 = new javax.swing.JPanel();
        pnlQuestao8 = new javax.swing.JPanel();
        lblQuestao5 = new javax.swing.JLabel();
        btn3a = new javax.swing.JButton();
        lbl3a = new javax.swing.JLabel();
        lbl3b = new javax.swing.JLabel();
        btn3b = new javax.swing.JButton();
        lbl3c = new javax.swing.JLabel();
        btn3c = new javax.swing.JButton();
        lbl3d = new javax.swing.JLabel();
        btn3d = new javax.swing.JButton();
        btnProximo6 = new javax.swing.JButton();
        btnAnterior2 = new javax.swing.JButton();
        pnlQuestao4 = new javax.swing.JPanel();
        lblQuestao4 = new javax.swing.JLabel();
        btnProximo4 = new javax.swing.JButton();
        lbl4c = new javax.swing.JLabel();
        btn4c = new javax.swing.JButton();
        lbl4b = new javax.swing.JLabel();
        btn4b = new javax.swing.JButton();
        btn4a = new javax.swing.JButton();
        lbl4a = new javax.swing.JLabel();
        lbl4d = new javax.swing.JLabel();
        btn4d = new javax.swing.JButton();
        btnAnterior3 = new javax.swing.JButton();
        pnlQuestao7 = new javax.swing.JPanel();
        lblQuestao6 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        lbl5a = new javax.swing.JLabel();
        btn5a = new javax.swing.JButton();
        btn5b = new javax.swing.JButton();
        lbl5b = new javax.swing.JLabel();
        lbl5c = new javax.swing.JLabel();
        btn5c = new javax.swing.JButton();
        lbl5d = new javax.swing.JLabel();
        btn5d = new javax.swing.JButton();
        btnAnterior4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPontos = new javax.swing.JLabel();
        lblParabens = new javax.swing.JLabel();
        btnRecomeçar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNomeParabens = new javax.swing.JLabel();
        lblParabens2 = new javax.swing.JLabel();
        lblPorcentagem = new javax.swing.JLabel();
        lblPorcentagemSimbolo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbpPrincipal.setToolTipText("");
        tbpPrincipal.setAlignmentX(0.0F);
        tbpPrincipal.setAlignmentY(0.0F);
        tbpPrincipal.setEnabled(false);
        tbpPrincipal.setRequestFocusEnabled(false);
        tbpPrincipal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbpPrincipalPropertyChange(evt);
            }
        });

        lblNome.setText("Digite seu nome:");

        txfNome.setText("                                    ");
        txfNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfNomeMouseClicked(evt);
            }
        });
        txfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNomeActionPerformed(evt);
            }
        });

        btnProximo1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnProximo1.setText(">");
        btnProximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo1ActionPerformed(evt);
            }
        });

        lblQuestao1.setText("Aqui vai escrito o enunciado da questão 1");

        txfQuestao1.setText("                                    ");
        txfQuestao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfQuestao1MouseClicked(evt);
            }
        });
        txfQuestao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfQuestao1ActionPerformed(evt);
            }
        });

        btnTeclado.setText("Teclado");
        btnTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestao1Layout = new javax.swing.GroupLayout(pnlQuestao1);
        pnlQuestao1.setLayout(pnlQuestao1Layout);
        pnlQuestao1Layout.setHorizontalGroup(
            pnlQuestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao1Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(pnlQuestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestao1Layout.createSequentialGroup()
                        .addComponent(btnProximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestao1Layout.createSequentialGroup()
                        .addGroup(pnlQuestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblQuestao1)
                            .addGroup(pnlQuestao1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlQuestao1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txfQuestao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(btnTeclado)))
                        .addGap(125, 125, 125))))
        );
        pnlQuestao1Layout.setVerticalGroup(
            pnlQuestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao1Layout.createSequentialGroup()
                .addGroup(pnlQuestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNome)
                    .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblQuestao1)
                .addGap(26, 26, 26)
                .addGroup(pnlQuestao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfQuestao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeclado))
                .addGap(18, 18, 18)
                .addComponent(btnProximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        tbpPrincipal.addTab("Questão 1", pnlQuestao1);

        lblQuestao2.setText("Aqui vai o enunciado da questão 2");

        txfQuestao2.setText("                                   ");
        txfQuestao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfQuestao2MouseClicked(evt);
            }
        });
        txfQuestao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfQuestao2ActionPerformed(evt);
            }
        });

        btnProximo2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnProximo2.setText(">");
        btnProximo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo2ActionPerformed(evt);
            }
        });

        btnAnterior1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnAnterior1.setText("<");
        btnAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior1ActionPerformed(evt);
            }
        });

        btnTeclado1.setText("Teclado");
        btnTeclado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeclado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestao2Layout = new javax.swing.GroupLayout(pnlQuestao2);
        pnlQuestao2.setLayout(pnlQuestao2Layout);
        pnlQuestao2Layout.setHorizontalGroup(
            pnlQuestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestao2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProximo2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestao2Layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(pnlQuestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblQuestao2)
                    .addGroup(pnlQuestao2Layout.createSequentialGroup()
                        .addComponent(txfQuestao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnTeclado1)))
                .addGap(184, 184, 184))
        );
        pnlQuestao2Layout.setVerticalGroup(
            pnlQuestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblQuestao2)
                .addGap(18, 18, 18)
                .addGroup(pnlQuestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfQuestao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeclado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pnlQuestao2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        tbpPrincipal.addTab("Questão 2", pnlQuestao2);

        lblQuestao5.setText("Aqui vai o enunciado da questão 3");

        btn3a.setText("a");
        btn3a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3aMouseClicked(evt);
            }
        });
        btn3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3aActionPerformed(evt);
            }
        });

        lbl3a.setText("PrimeiraOpção");

        lbl3b.setText("SegundaOpção");

        btn3b.setText("b");
        btn3b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3bMouseClicked(evt);
            }
        });
        btn3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3bActionPerformed(evt);
            }
        });

        lbl3c.setText("TerceiraOpção");

        btn3c.setText("c");
        btn3c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3cMouseClicked(evt);
            }
        });
        btn3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3cActionPerformed(evt);
            }
        });

        lbl3d.setText("QuartaOpção");

        btn3d.setText("d");
        btn3d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3dMouseClicked(evt);
            }
        });
        btn3d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3dActionPerformed(evt);
            }
        });

        btnProximo6.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnProximo6.setText(">");
        btnProximo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestao8Layout = new javax.swing.GroupLayout(pnlQuestao8);
        pnlQuestao8.setLayout(pnlQuestao8Layout);
        pnlQuestao8Layout.setHorizontalGroup(
            pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao8Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btn3a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuestao8Layout.createSequentialGroup()
                        .addComponent(lbl3a)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlQuestao8Layout.createSequentialGroup()
                        .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl3b)
                            .addComponent(lbl3c))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(btnProximo6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(pnlQuestao8Layout.createSequentialGroup()
                .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuestao8Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblQuestao5))
                    .addGroup(pnlQuestao8Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn3c)
                            .addComponent(btn3b)
                            .addGroup(pnlQuestao8Layout.createSequentialGroup()
                                .addComponent(btn3d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl3d)))))
                .addContainerGap())
        );
        pnlQuestao8Layout.setVerticalGroup(
            pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestao5)
                .addGap(62, 62, 62)
                .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3a)
                    .addComponent(lbl3a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnProximo6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(pnlQuestao8Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3b)
                    .addComponent(lbl3b))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3c)
                    .addComponent(lbl3c))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlQuestao8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3d)
                    .addComponent(lbl3d))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAnterior2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnAnterior2.setText("<");
        btnAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestao5Layout = new javax.swing.GroupLayout(pnlQuestao5);
        pnlQuestao5.setLayout(pnlQuestao5Layout);
        pnlQuestao5Layout.setHorizontalGroup(
            pnlQuestao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pnlQuestao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pnlQuestao5Layout.setVerticalGroup(
            pnlQuestao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao5Layout.createSequentialGroup()
                .addGroup(pnlQuestao5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuestao5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlQuestao8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQuestao5Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        tbpPrincipal.addTab("Questão 3", pnlQuestao5);

        lblQuestao4.setText("Aqui vai o enunciado da questão 4");

        btnProximo4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnProximo4.setText(">");
        btnProximo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximo4ActionPerformed(evt);
            }
        });

        lbl4c.setText("TerceiraOpção");

        btn4c.setText("c");
        btn4c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4cMouseClicked(evt);
            }
        });
        btn4c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4cActionPerformed(evt);
            }
        });

        lbl4b.setText("SegundaOpção");

        btn4b.setText("b");
        btn4b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4bMouseClicked(evt);
            }
        });
        btn4b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4bActionPerformed(evt);
            }
        });

        btn4a.setText("a");
        btn4a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4aMouseClicked(evt);
            }
        });
        btn4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4aActionPerformed(evt);
            }
        });

        lbl4a.setText("PrimeiraOpção");

        lbl4d.setText("QuartaOpção");

        btn4d.setText("d");
        btn4d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4dMouseClicked(evt);
            }
        });
        btn4d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4dActionPerformed(evt);
            }
        });

        btnAnterior3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnAnterior3.setText("<");
        btnAnterior3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestao4Layout = new javax.swing.GroupLayout(pnlQuestao4);
        pnlQuestao4.setLayout(pnlQuestao4Layout);
        pnlQuestao4Layout.setHorizontalGroup(
            pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao4Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(lblQuestao4)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestao4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAnterior3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProximo4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlQuestao4Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlQuestao4Layout.createSequentialGroup()
                            .addComponent(btn4c)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl4c))
                        .addGroup(pnlQuestao4Layout.createSequentialGroup()
                            .addComponent(btn4b)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl4b))
                        .addGroup(pnlQuestao4Layout.createSequentialGroup()
                            .addComponent(btn4d)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl4d))
                        .addGroup(pnlQuestao4Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(btn4a)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl4a)))
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        pnlQuestao4Layout.setVerticalGroup(
            pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestao4)
                .addGap(109, 109, 109)
                .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlQuestao4Layout.createSequentialGroup()
                    .addGap(99, 99, 99)
                    .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4a)
                        .addComponent(lbl4a))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4b)
                        .addComponent(lbl4b))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4c)
                        .addComponent(lbl4c))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnlQuestao4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4d)
                        .addComponent(lbl4d))
                    .addContainerGap(130, Short.MAX_VALUE)))
        );

        tbpPrincipal.addTab("Questão 4", pnlQuestao4);

        lblQuestao6.setText("Aqui vai o enunciado da questão 5");

        btnFinalizar.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lbl5a.setText("PrimeiraOpção");

        btn5a.setText("a");
        btn5a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5aMouseClicked(evt);
            }
        });
        btn5a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5aActionPerformed(evt);
            }
        });

        btn5b.setText("b");
        btn5b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5bMouseClicked(evt);
            }
        });
        btn5b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5bActionPerformed(evt);
            }
        });

        lbl5b.setText("SegundaOpção");

        lbl5c.setText("TerceiraOpção");

        btn5c.setText("c");
        btn5c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5cMouseClicked(evt);
            }
        });
        btn5c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5cActionPerformed(evt);
            }
        });

        lbl5d.setText("QuartaOpção");

        btn5d.setText("d");
        btn5d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5dMouseClicked(evt);
            }
        });
        btn5d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5dActionPerformed(evt);
            }
        });

        btnAnterior4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnAnterior4.setText("<");
        btnAnterior4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnterior4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlQuestao7Layout = new javax.swing.GroupLayout(pnlQuestao7);
        pnlQuestao7.setLayout(pnlQuestao7Layout);
        pnlQuestao7Layout.setHorizontalGroup(
            pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAnterior4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblQuestao6)
                    .addGroup(pnlQuestao7Layout.createSequentialGroup()
                        .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn5a, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn5c)
                            .addComponent(btn5b)
                            .addComponent(btn5d))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl5a)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQuestao7Layout.createSequentialGroup()
                                    .addComponent(lbl5c)
                                    .addGap(1, 1, 1)))
                            .addComponent(lbl5b)
                            .addComponent(lbl5d))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlQuestao7Layout.setVerticalGroup(
            pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuestao7Layout.createSequentialGroup()
                .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlQuestao7Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlQuestao7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuestao6)
                        .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlQuestao7Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnAnterior4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlQuestao7Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlQuestao7Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(lbl5c))
                                    .addGroup(pnlQuestao7Layout.createSequentialGroup()
                                        .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lbl5a)
                                            .addComponent(btn5a))
                                        .addGap(3, 3, 3)
                                        .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn5b)
                                            .addComponent(lbl5b))
                                        .addGap(3, 3, 3)
                                        .addComponent(btn5c)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlQuestao7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn5d)
                                    .addComponent(lbl5d))))))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        tbpPrincipal.addTab("Questão5", pnlQuestao7);

        lblPontos.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        lblPontos.setText("X");

        lblParabens.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblParabens.setText("Parabens");

        btnRecomeçar.setText("Refazer");
        btnRecomeçar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomeçarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        jLabel1.setText("/5");

        lblNomeParabens.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblNomeParabens.setText("Nome");

        lblParabens2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblParabens2.setText("Parabens2");

        lblPorcentagem.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        lblPorcentagem.setText("X");

        lblPorcentagemSimbolo.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        lblPorcentagemSimbolo.setText("%");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecomeçar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblParabens)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomeParabens))
                            .addComponent(lblParabens2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(lblPorcentagem)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPorcentagemSimbolo)
                .addGap(165, 165, 165))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblPorcentagem)
                    .addComponent(lblPorcentagemSimbolo))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeParabens)
                    .addComponent(lblParabens))
                .addGap(18, 18, 18)
                .addComponent(lblParabens2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnRecomeçar)
                .addGap(59, 59, 59))
        );

        tbpPrincipal.addTab("Resultados", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbpPrincipalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbpPrincipalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpPrincipalPropertyChange

    private void btnRecomeçarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomeçarActionPerformed
        txfNome.setText("          ");
        txfQuestao1.setText("          ");
        txfQuestao2.setText("          ");
        
        tbpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_btnRecomeçarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        Estaticos.MENSAGEM ="";
                
        resQuestão3= Estaticos.Questão3;
        resQuestão4= Estaticos.Questão4;
        resQuestão5= Estaticos.Questão5;
        
        Controle controle = new Controle(txfNome.getText(), txfQuestao1.getText().toUpperCase(),
            txfQuestao2.getText().toUpperCase(),resQuestão3,resQuestão4, resQuestão5);
         
        
        if(Estaticos.MENSAGEM.equals(""))
        {
            String pontos ="";
            for(ArrayList<String> Visitante  : Estaticos.DadosPessoas)
            {
                AnalisaDados analisadados= new AnalisaDados(null,null, null, null,null, null);
                pontos =Visitante.get(6);
            }
            
            Integer IntPontos =Integer.valueOf(pontos);
            if(IntPontos >=3 )
            {
                lblParabens.setText("Parabens ");
                lblNomeParabens.setText(txfNome.getText());
                lblParabens2.setText("você conhece bem sobre a as expedições de marte");
                
            }
            else
            {
                lblParabens.setText("Sinto Muito");
                lblNomeParabens.setText(txfNome.getText());
                lblParabens2.setText("Você precisa aprender mais sobre marte");
            }
            lblPontos.setText(pontos);
            lblPorcentagem.setText(Estaticos.PORCENTAGEM);
            
            tbpPrincipal.setSelectedIndex(5);
        }
        else
        {
            JOptionPane.showMessageDialog(null, Estaticos.MENSAGEM);
        }
        
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnProximo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo4ActionPerformed
        // TODO add your handling code here:
        tbpPrincipal.setSelectedIndex(4);
    }//GEN-LAST:event_btnProximo4ActionPerformed

    private void btn3dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3dActionPerformed

    private void btn3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3cActionPerformed

    private void btn3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3bActionPerformed
        
    }//GEN-LAST:event_btn3bActionPerformed

    private void btn3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3aActionPerformed
        
        
    }//GEN-LAST:event_btn3aActionPerformed

    private void btnProximo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo6ActionPerformed
        tbpPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_btnProximo6ActionPerformed

    private void btnTeclado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeclado1ActionPerformed
        Estaticos.TEXTO = txfQuestao2.getText();
        Teclado tecla = new Teclado(null, true);
        tecla.setVisible(true);
        txfQuestao2.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_btnTeclado1ActionPerformed

    private void btnAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior1ActionPerformed
        tbpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_btnAnterior1ActionPerformed

    private void btnProximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo2ActionPerformed
        // TODO add your handling code here:
        tbpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_btnProximo2ActionPerformed

    private void txfQuestao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfQuestao2ActionPerformed

    }//GEN-LAST:event_txfQuestao2ActionPerformed

    private void btnTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecladoActionPerformed
        Estaticos.TEXTO = txfQuestao1.getText();
        Teclado tecla = new Teclado(null, true);
        tecla.setVisible(true);
        txfQuestao1.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_btnTecladoActionPerformed

    private void txfQuestao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfQuestao1ActionPerformed

    }//GEN-LAST:event_txfQuestao1ActionPerformed

    private void btnProximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo1ActionPerformed
        // TODO add your handling code here:
        tbpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnProximo1ActionPerformed

    private void txfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeActionPerformed

    }//GEN-LAST:event_txfNomeActionPerformed

    private void txfNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfNomeMouseClicked

        Estaticos.TEXTO = txfNome.getText();
        Teclado tecla = new Teclado(null, true);
        tecla.setVisible(true);
        txfNome.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_txfNomeMouseClicked

    private void btn4cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4cActionPerformed

    private void btn4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4bActionPerformed

    private void btn4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4aActionPerformed

    private void btn4dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4dActionPerformed

    private void btn5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5aActionPerformed

    private void btn5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5bActionPerformed

    private void btn5cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5cActionPerformed

    private void btn5dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5dActionPerformed

    private void btn3aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3aMouseClicked
        Estaticos.Questão3 = "a";
        resQuestão3 = Estaticos.Questão3;
        btn3a.setBackground(Color.GREEN);
        btn3b.setBackground(Color.WHITE);
        btn3c.setBackground(Color.WHITE);
        btn3d.setBackground(Color.WHITE);
       
    }//GEN-LAST:event_btn3aMouseClicked

    private void btn3bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3bMouseClicked
        Estaticos.Questão3 = "b";
        resQuestão3 = Estaticos.Questão3;
        btn3b.setBackground(Color.GREEN);
        btn3a.setBackground(Color.WHITE);
        btn3c.setBackground(Color.WHITE);
        btn3d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn3bMouseClicked

    private void btn3cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3cMouseClicked
        Estaticos.Questão3 = "c";
        resQuestão3 = Estaticos.Questão3;
        btn3c.setBackground(Color.GREEN);
        btn3a.setBackground(Color.WHITE);
        btn3b.setBackground(Color.WHITE);
        btn3d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn3cMouseClicked

    private void btn3dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3dMouseClicked
        Estaticos.Questão3 = "d";
        resQuestão3 = Estaticos.Questão3;
        btn3d.setBackground(Color.GREEN);
        btn3a.setBackground(Color.WHITE);
        btn3b.setBackground(Color.WHITE);
        btn3c.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn3dMouseClicked

    private void btn4aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4aMouseClicked
        Estaticos.Questão4 = "a";
        resQuestão4 = Estaticos.Questão4;
        btn4a.setBackground(Color.GREEN);
        btn4b.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);
        btn4d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn4aMouseClicked

    private void btn4bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4bMouseClicked
        Estaticos.Questão4 = "b";
        resQuestão4 = Estaticos.Questão4;
        btn4b.setBackground(Color.GREEN);
        btn4a.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);
        btn4d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn4bMouseClicked

    private void btn4cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4cMouseClicked
        Estaticos.Questão4 = "c";
        resQuestão4 = Estaticos.Questão4;
        btn4c.setBackground(Color.GREEN);
        btn4a.setBackground(Color.WHITE);
        btn4b.setBackground(Color.WHITE);
        btn4d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn4cMouseClicked

    private void btn4dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4dMouseClicked
        Estaticos.Questão4 = "d";
        resQuestão4 = Estaticos.Questão4;
        btn4d.setBackground(Color.GREEN);
        btn4a.setBackground(Color.WHITE);
        btn4b.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_btn4dMouseClicked

    private void btn5aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5aMouseClicked
        Estaticos.Questão5 = "a";
        resQuestão5 = Estaticos.Questão5;
        btn5a.setBackground(Color.GREEN);
        btn5b.setBackground(Color.WHITE);
        btn5c.setBackground(Color.WHITE);
        btn5d.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_btn5aMouseClicked

    private void btn5bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5bMouseClicked
        
        Estaticos.Questão5 = "b";
        resQuestão5 = Estaticos.Questão5;
        btn5b.setBackground(Color.GREEN);
        btn5a.setBackground(Color.WHITE);
        btn5c.setBackground(Color.WHITE);
        btn5d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn5bMouseClicked

    private void btn5cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5cMouseClicked
        Estaticos.Questão5 = "c";
        resQuestão5 = Estaticos.Questão5;
        btn5c.setBackground(Color.GREEN);
        btn5a.setBackground(Color.WHITE);
        btn5b.setBackground(Color.WHITE);
        btn5d.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn5cMouseClicked

    private void btn5dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5dMouseClicked
        Estaticos.Questão5 = "d";
        resQuestão5 = Estaticos.Questão5;
        btn5d.setBackground(Color.GREEN);
        btn5a.setBackground(Color.WHITE);
        btn5b.setBackground(Color.WHITE);
        btn5c.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn5dMouseClicked

    private void btnAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior2ActionPerformed
        tbpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnAnterior2ActionPerformed

    private void btnAnterior3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior3ActionPerformed
       tbpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_btnAnterior3ActionPerformed

    private void btnAnterior4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior4ActionPerformed
        tbpPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_btnAnterior4ActionPerformed

    private void txfQuestao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfQuestao1MouseClicked
        Estaticos.TEXTO = txfQuestao1.getText();
        Teclado tecla = new Teclado(null, true);
        tecla.setVisible(true);
        txfQuestao1.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_txfQuestao1MouseClicked

    private void txfQuestao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfQuestao2MouseClicked
        Estaticos.TEXTO = txfQuestao2.getText();
        Teclado tecla = new Teclado(null, true);
        tecla.setVisible(true);
        txfQuestao2.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_txfQuestao2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgQuestao4;
    private javax.swing.ButtonGroup btgQuestao5;
    private javax.swing.JButton btn3a;
    private javax.swing.JButton btn3b;
    private javax.swing.JButton btn3c;
    private javax.swing.JButton btn3d;
    private javax.swing.JButton btn4a;
    private javax.swing.JButton btn4b;
    private javax.swing.JButton btn4c;
    private javax.swing.JButton btn4d;
    private javax.swing.JButton btn5a;
    private javax.swing.JButton btn5b;
    private javax.swing.JButton btn5c;
    private javax.swing.JButton btn5d;
    private javax.swing.JButton btnAnterior1;
    private javax.swing.JButton btnAnterior2;
    private javax.swing.JButton btnAnterior3;
    private javax.swing.JButton btnAnterior4;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnProximo1;
    private javax.swing.JButton btnProximo2;
    private javax.swing.JButton btnProximo4;
    private javax.swing.JButton btnProximo6;
    private javax.swing.JButton btnRecomeçar;
    private javax.swing.JButton btnTeclado;
    private javax.swing.JButton btnTeclado1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl3a;
    private javax.swing.JLabel lbl3b;
    private javax.swing.JLabel lbl3c;
    private javax.swing.JLabel lbl3d;
    private javax.swing.JLabel lbl4a;
    private javax.swing.JLabel lbl4b;
    private javax.swing.JLabel lbl4c;
    private javax.swing.JLabel lbl4d;
    private javax.swing.JLabel lbl5a;
    private javax.swing.JLabel lbl5b;
    private javax.swing.JLabel lbl5c;
    private javax.swing.JLabel lbl5d;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeParabens;
    private javax.swing.JLabel lblParabens;
    private javax.swing.JLabel lblParabens2;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPorcentagem;
    private javax.swing.JLabel lblPorcentagemSimbolo;
    private javax.swing.JLabel lblQuestao1;
    private javax.swing.JLabel lblQuestao2;
    private javax.swing.JLabel lblQuestao4;
    private javax.swing.JLabel lblQuestao5;
    private javax.swing.JLabel lblQuestao6;
    private javax.swing.JPanel pnlQuestao1;
    private javax.swing.JPanel pnlQuestao2;
    private javax.swing.JPanel pnlQuestao4;
    private javax.swing.JPanel pnlQuestao5;
    private javax.swing.JPanel pnlQuestao7;
    private javax.swing.JPanel pnlQuestao8;
    private javax.swing.JTabbedPane tbpPrincipal;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfQuestao1;
    private javax.swing.JTextField txfQuestao2;
    // End of variables declaration//GEN-END:variables
}
