package Apresentacao;

import Modelos.AnalisaDados;
import Modelos.Controle;
import Modelos.Estaticos;
import static Modelos.Estaticos.DadosPessoas;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class frmPrincipal extends javax.swing.JDialog
{

    String resQuestão3 = "";
    String resQuestão4 = "";
    String resQuestão5 = "";

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        Estaticos.Questão3 = "";
        Estaticos.Questão4 = "";
        Estaticos.Questão5 = "";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btgQuestao4 = new javax.swing.ButtonGroup();
        btgQuestao5 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tbpPrincipal = new javax.swing.JTabbedPane();
        pnlQuestao1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        btnProximo1 = new javax.swing.JButton();
        lblQuestao1 = new javax.swing.JLabel();
        txfQuestao1 = new javax.swing.JTextField();
        lblQuestão1nL = new javax.swing.JLabel();
        lblRespondaSN = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlQuestao2 = new javax.swing.JPanel();
        lblQuestao2 = new javax.swing.JLabel();
        txfQuestao2 = new javax.swing.JTextField();
        btnProximo2 = new javax.swing.JButton();
        btnAnterior1 = new javax.swing.JButton();
        lblRespondaSN2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlQuestao3 = new javax.swing.JPanel();
        lblQuestao5 = new javax.swing.JLabel();
        btn3a = new javax.swing.JButton();
        lbl3a = new javax.swing.JLabel();
        lbl3b = new javax.swing.JLabel();
        btn3b = new javax.swing.JButton();
        lbl3c = new javax.swing.JLabel();
        btn3c = new javax.swing.JButton();
        btnProximo6 = new javax.swing.JButton();
        btnAnterior2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlQuestao4 = new javax.swing.JPanel();
        lblQuestao4 = new javax.swing.JLabel();
        btnProximo4 = new javax.swing.JButton();
        lbl4c = new javax.swing.JLabel();
        btn4c = new javax.swing.JButton();
        lbl4b = new javax.swing.JLabel();
        btn4b = new javax.swing.JButton();
        btn4a = new javax.swing.JButton();
        lbl4a = new javax.swing.JLabel();
        btnAnterior3 = new javax.swing.JButton();
        lblQuestão4nL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlQuestao5 = new javax.swing.JPanel();
        lblQuestao6 = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        lbl5a = new javax.swing.JLabel();
        btn5a = new javax.swing.JButton();
        btn5b = new javax.swing.JButton();
        lbl5b = new javax.swing.JLabel();
        lbl5c = new javax.swing.JLabel();
        btn5c = new javax.swing.JButton();
        btnAnterior4 = new javax.swing.JButton();
        lblQustão5nL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlResultado = new javax.swing.JPanel();
        lblPontos = new javax.swing.JLabel();
        lblParabens = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNomeParabens = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNomeVis = new javax.swing.JLabel();
        lblQ1Vis = new javax.swing.JLabel();
        lblQ2Vis = new javax.swing.JLabel();
        lblQ3Vis = new javax.swing.JLabel();
        lblQ4Vis = new javax.swing.JLabel();
        lblResNome = new javax.swing.JLabel();
        lblResQ1 = new javax.swing.JLabel();
        lblResQ2 = new javax.swing.JLabel();
        lblResQ3 = new javax.swing.JLabel();
        lblResQ4 = new javax.swing.JLabel();
        lblResQ5 = new javax.swing.JLabel();
        lblQ5Vis = new javax.swing.JLabel();
        lblValorVisitante = new javax.swing.JLabel();
        lblPorcentagem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblParabens2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Questionario");

        tbpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        tbpPrincipal.setToolTipText("");
        tbpPrincipal.setAlignmentX(0.0F);
        tbpPrincipal.setAlignmentY(0.0F);
        tbpPrincipal.setEnabled(false);
        tbpPrincipal.setFont(new java.awt.Font("Helvetica", 0, 15)); // NOI18N
        tbpPrincipal.setPreferredSize(new java.awt.Dimension(1366, 768));
        tbpPrincipal.setRequestFocusEnabled(false);
        tbpPrincipal.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                tbpPrincipalPropertyChange(evt);
            }
        });

        pnlQuestao1.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuestao1.setName(""); // NOI18N
        pnlQuestao1.setPreferredSize(new java.awt.Dimension(1366, 768));
        pnlQuestao1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setBackground(new java.awt.Color(255, 255, 255));
        lblNome.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Digite seu nome:");
        pnlQuestao1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txfNome.setText("                                    ");
        txfNome.setSelectionColor(new java.awt.Color(102, 153, 255));
        txfNome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                txfNomeMouseClicked(evt);
            }
        });
        txfNome.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfNomeActionPerformed(evt);
            }
        });
        pnlQuestao1.add(txfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 200, 30));

        btnProximo1.setBackground(new java.awt.Color(54, 255, 131));
        btnProximo1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnProximo1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProximo1ActionPerformed(evt);
            }
        });
        pnlQuestao1.add(btnProximo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 230, 120, 180));

        lblQuestao1.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestao1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestao1.setText("Marte é o  quarto planeta do sistema solar a partir do Sol ");
        pnlQuestao1.add(lblQuestao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        txfQuestao1.setText("                                    ");
        txfQuestao1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                txfQuestao1MouseClicked(evt);
            }
        });
        txfQuestao1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfQuestao1ActionPerformed(evt);
            }
        });
        pnlQuestao1.add(txfQuestao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 160, 40));

        lblQuestão1nL.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestão1nL.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestão1nL.setText("e está localizado entre a Terra e Júpiter ? ");
        pnlQuestao1.add(lblQuestão1nL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 910, 40));

        lblRespondaSN.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lblRespondaSN.setForeground(new java.awt.Color(255, 255, 255));
        lblRespondaSN.setText("Responda apenas com sim ou nao!");
        pnlQuestao1.add(lblRespondaSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarsBackGround.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        pnlQuestao1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -40, 1890, 1040));

        tbpPrincipal.addTab("Questão 1", pnlQuestao1);

        pnlQuestao2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestao2.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestao2.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestao2.setText("Aqui vai o enunciado da questão 2");
        pnlQuestao2.add(lblQuestao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 840, -1));

        txfQuestao2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        txfQuestao2.setText("                                   ");
        txfQuestao2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                txfQuestao2MouseClicked(evt);
            }
        });
        txfQuestao2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txfQuestao2ActionPerformed(evt);
            }
        });
        pnlQuestao2.add(txfQuestao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 210, 70));

        btnProximo2.setFont(new java.awt.Font("DejaVu Sans", 0, 48)); // NOI18N
        btnProximo2.setText(">");
        btnProximo2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProximo2ActionPerformed(evt);
            }
        });
        pnlQuestao2.add(btnProximo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 120, 180));

        btnAnterior1.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        btnAnterior1.setText("<");
        btnAnterior1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnterior1ActionPerformed(evt);
            }
        });
        pnlQuestao2.add(btnAnterior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 247, 120, 180));

        lblRespondaSN2.setBackground(new java.awt.Color(255, 255, 255));
        lblRespondaSN2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lblRespondaSN2.setForeground(new java.awt.Color(255, 255, 255));
        lblRespondaSN2.setText("Responda apenas com sim ou nao!");
        pnlQuestao2.add(lblRespondaSN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarsBackGround.jpg"))); // NOI18N
        jLabel4.setText("jLabel3");
        pnlQuestao2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1890, 1040));

        tbpPrincipal.addTab("Questão 2", pnlQuestao2);

        pnlQuestao3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestao5.setBackground(new java.awt.Color(255, 255, 255));
        lblQuestao5.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestao5.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestao5.setText("Quais foram os veículos robóticos   lançados a Marte?");
        pnlQuestao3.add(lblQuestao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        btn3a.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        btn3a.setText("A");
        btn3a.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn3aMouseClicked(evt);
            }
        });
        btn3a.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn3aActionPerformed(evt);
            }
        });
        pnlQuestao3.add(btn3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, 90));

        lbl3a.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbl3a.setForeground(new java.awt.Color(255, 255, 255));
        lbl3a.setText("Perseverance,Curiosity,Sojourner, Spirit e Opportunity");
        pnlQuestao3.add(lbl3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 590, 25));

        lbl3b.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbl3b.setForeground(new java.awt.Color(255, 255, 255));
        lbl3b.setText(" Opala,LEV-2, Smart,Lunokhod 1 e Yutu");
        pnlQuestao3.add(lbl3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 570, -1));

        btn3b.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        btn3b.setText("B");
        btn3b.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn3bMouseClicked(evt);
            }
        });
        btn3b.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn3bActionPerformed(evt);
            }
        });
        pnlQuestao3.add(btn3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 110, 90));

        lbl3c.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbl3c.setForeground(new java.awt.Color(255, 255, 255));
        lbl3c.setText("Spirit ,Smart , Perseverance ,LEV-2 e Opportunity");
        pnlQuestao3.add(lbl3c, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 570, 20));

        btn3c.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        btn3c.setText("C");
        btn3c.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn3cMouseClicked(evt);
            }
        });
        btn3c.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn3cActionPerformed(evt);
            }
        });
        pnlQuestao3.add(btn3c, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 110, 90));

        btnProximo6.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        btnProximo6.setText(">");
        btnProximo6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProximo6ActionPerformed(evt);
            }
        });
        pnlQuestao3.add(btnProximo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 300, 70, 150));

        btnAnterior2.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        btnAnterior2.setText("<");
        btnAnterior2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnterior2ActionPerformed(evt);
            }
        });
        pnlQuestao3.add(btnAnterior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarsBackGround.jpg"))); // NOI18N
        jLabel5.setText("jLabel3");
        pnlQuestao3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1890, 1040));

        tbpPrincipal.addTab("Questão 3", pnlQuestao3);

        pnlQuestao4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestao4.setBackground(new java.awt.Color(255, 255, 255));
        lblQuestao4.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestao4.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestao4.setText("O veículo robótico Sojourner teve seu nome dado em ");
        pnlQuestao4.add(lblQuestao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btnProximo4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnProximo4.setText(">");
        btnProximo4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProximo4ActionPerformed(evt);
            }
        });
        pnlQuestao4.add(btnProximo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 270, 100, 150));

        lbl4c.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbl4c.setForeground(new java.awt.Color(255, 255, 255));
        lbl4c.setText("Selena Gomez");
        pnlQuestao4.add(lbl4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        btn4c.setText("C");
        btn4c.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn4cMouseClicked(evt);
            }
        });
        btn4c.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn4cActionPerformed(evt);
            }
        });
        pnlQuestao4.add(btn4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 110, 90));

        lbl4b.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbl4b.setForeground(new java.awt.Color(255, 255, 255));
        lbl4b.setText("Silvester Stallone");
        pnlQuestao4.add(lbl4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        btn4b.setText("B");
        btn4b.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn4bMouseClicked(evt);
            }
        });
        btn4b.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn4bActionPerformed(evt);
            }
        });
        pnlQuestao4.add(btn4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 110, 90));

        btn4a.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        btn4a.setText("A");
        btn4a.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn4aMouseClicked(evt);
            }
        });
        btn4a.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn4aActionPerformed(evt);
            }
        });
        pnlQuestao4.add(btn4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 110, 90));

        lbl4a.setFont(new java.awt.Font("Helvetica", 0, 24)); // NOI18N
        lbl4a.setForeground(new java.awt.Color(255, 255, 255));
        lbl4a.setText("Sojourner Thruth");
        pnlQuestao4.add(lbl4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 50));

        btnAnterior3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnAnterior3.setText("<");
        btnAnterior3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnterior3ActionPerformed(evt);
            }
        });
        pnlQuestao4.add(btnAnterior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 160));

        lblQuestão4nL.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestão4nL.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestão4nL.setText("homenagem a qual celebridade?");
        pnlQuestao4.add(lblQuestão4nL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarsBackGround.jpg"))); // NOI18N
        jLabel6.setText("jLabel3");
        pnlQuestao4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1890, 1040));

        tbpPrincipal.addTab("Questão 4", pnlQuestao4);

        pnlQuestao5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestao6.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQuestao6.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestao6.setText("Quais foram os veículos robóticos gêmeos lançados ");
        pnlQuestao5.add(lblQuestao6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        btnFinalizar.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinalizarActionPerformed(evt);
            }
        });
        pnlQuestao5.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 150, 80));

        lbl5a.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        lbl5a.setForeground(new java.awt.Color(255, 255, 255));
        lbl5a.setText("Sprite e Pepsi");
        pnlQuestao5.add(lbl5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, 50));

        btn5a.setText("A");
        btn5a.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn5aMouseClicked(evt);
            }
        });
        btn5a.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn5aActionPerformed(evt);
            }
        });
        pnlQuestao5.add(btn5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 110, 90));

        btn5b.setText("B");
        btn5b.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn5bMouseClicked(evt);
            }
        });
        btn5b.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn5bActionPerformed(evt);
            }
        });
        pnlQuestao5.add(btn5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 110, 90));

        lbl5b.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        lbl5b.setForeground(new java.awt.Color(255, 255, 255));
        lbl5b.setText("Opala e Smart");
        pnlQuestao5.add(lbl5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        lbl5c.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        lbl5c.setForeground(new java.awt.Color(255, 255, 255));
        lbl5c.setText("Spirit e Opportunity");
        pnlQuestao5.add(lbl5c, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        btn5c.setText("C");
        btn5c.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btn5cMouseClicked(evt);
            }
        });
        btn5c.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn5cActionPerformed(evt);
            }
        });
        pnlQuestao5.add(btn5c, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 110, 90));

        btnAnterior4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnAnterior4.setText("<");
        btnAnterior4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAnterior4ActionPerformed(evt);
            }
        });
        pnlQuestao5.add(btnAnterior4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 160));

        lblQustão5nL.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblQustão5nL.setForeground(new java.awt.Color(255, 255, 255));
        lblQustão5nL.setText("em missão a marte em 2003?");
        pnlQuestao5.add(lblQustão5nL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 81, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarsBackGround.jpg"))); // NOI18N
        jLabel7.setText("jLabel3");
        pnlQuestao5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1890, 1040));

        tbpPrincipal.addTab("Questão5", pnlQuestao5);

        pnlResultado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPontos.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblPontos.setForeground(new java.awt.Color(255, 255, 255));
        lblPontos.setText("X");
        pnlResultado.add(lblPontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 52));

        lblParabens.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lblParabens.setForeground(new java.awt.Color(255, 255, 255));
        lblParabens.setText("Parabens,");
        pnlResultado.add(lblParabens, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("/5");
        pnlResultado.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        lblNomeParabens.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lblNomeParabens.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeParabens.setText("Nome");
        pnlResultado.add(lblNomeParabens, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jButton1.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButton1.setText("Voltar para o inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        pnlResultado.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 140));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeVis.setText("Nome");

        lblQ1Vis.setText("Questão 1");

        lblQ2Vis.setText("Questão 2");

        lblQ3Vis.setText("Questão 3");

        lblQ4Vis.setText("Questão 4");

        lblResNome.setText("jLabel15");

        lblResQ1.setText("jLabel16");

        lblResQ2.setText("jLabel17");

        lblResQ3.setText("jLabel18");

        lblResQ4.setText("jLabel19");

        lblResQ5.setText("jLabel19");

        lblQ5Vis.setText("Questão 5");

        lblValorVisitante.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblValorVisitante.setText("X");

        lblPorcentagem.setFont(new java.awt.Font("Helvetica", 0, 48)); // NOI18N
        lblPorcentagem.setText("%");

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel8.setText("Sua pontuação em relaçao aos outros");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setText("Visitante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQ5Vis)
                                .addGap(18, 18, 18)
                                .addComponent(lblResQ5))
                            .addComponent(lblQ4Vis)
                            .addComponent(lblQ3Vis)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblNomeVis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(39, 39, 39)
                                    .addComponent(lblResNome))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblQ2Vis, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblQ1Vis))
                                    .addGap(3, 3, 3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblResQ2)
                                        .addComponent(lblResQ1)
                                        .addComponent(lblResQ3)
                                        .addComponent(lblResQ4))))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeVis)
                    .addComponent(lblResNome))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ1Vis)
                    .addComponent(lblResQ1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ2Vis)
                    .addComponent(lblResQ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ3Vis)
                    .addComponent(lblResQ3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ4Vis)
                    .addComponent(lblResQ4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQ5Vis)
                    .addComponent(lblResQ5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlResultado.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 510, 370));

        lblParabens2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        lblParabens2.setForeground(new java.awt.Color(255, 255, 255));
        lblParabens2.setText("Parabens2");
        pnlResultado.add(lblParabens2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 470, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MarsBackGround.jpg"))); // NOI18N
        jLabel9.setText("jLabel3");
        pnlResultado.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1890, 1040));

        tbpPrincipal.addTab("Resultados", pnlResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbpPrincipalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbpPrincipalPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpPrincipalPropertyChange

    private void btnAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior2ActionPerformed
        tbpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnAnterior2ActionPerformed

    private void btnProximo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo6ActionPerformed
        tbpPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_btnProximo6ActionPerformed

    private void btn3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3cActionPerformed
        Estaticos.Questão3 = "c";
        resQuestão3 = Estaticos.Questão3;
        btn3a.setBackground(Color.GRAY);
        btn3b.setBackground(Color.WHITE);
        btn3c.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn3cActionPerformed

    private void btn3cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3cMouseClicked

    }//GEN-LAST:event_btn3cMouseClicked

    private void btn3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3bActionPerformed
        Estaticos.Questão3 = "b";
        resQuestão3 = Estaticos.Questão3;
        btn3b.setBackground(Color.GRAY);
        btn3c.setBackground(Color.WHITE);
        btn3a.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn3bActionPerformed

    private void btn3bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3bMouseClicked

    }//GEN-LAST:event_btn3bMouseClicked

    private void btn3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3aActionPerformed
        Estaticos.Questão3 = "a";
        resQuestão3 = Estaticos.Questão3;
        btn3a.setBackground(Color.GRAY);
        btn3b.setBackground(Color.WHITE);
        btn3c.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn3aActionPerformed

    private void btn3aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3aMouseClicked

    }//GEN-LAST:event_btn3aMouseClicked

    private void btnAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior1ActionPerformed
        tbpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_btnAnterior1ActionPerformed

    private void btnProximo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo2ActionPerformed
        // TODO add your handling code here:
        tbpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_btnProximo2ActionPerformed

    private void txfQuestao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfQuestao2ActionPerformed

    }//GEN-LAST:event_txfQuestao2ActionPerformed

    private void txfQuestao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfQuestao2MouseClicked
        Estaticos.TEXTO = txfQuestao2.getText();
        frmTecladoSimNao teclaSN;
        teclaSN = new frmTecladoSimNao(null, true);
        teclaSN.setVisible(true);
        txfQuestao2.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_txfQuestao2MouseClicked

    private void txfQuestao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfQuestao1ActionPerformed

    }//GEN-LAST:event_txfQuestao1ActionPerformed

    private void txfQuestao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfQuestao1MouseClicked
        Estaticos.TEXTO = txfQuestao1.getText();
        frmTecladoSimNao teclaSN = new frmTecladoSimNao(null, true);
        teclaSN.setVisible(true);
        txfQuestao1.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_txfQuestao1MouseClicked

    private void btnProximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo1ActionPerformed
        // TODO add your handling code here:
        tbpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_btnProximo1ActionPerformed

    private void txfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeActionPerformed

    }//GEN-LAST:event_txfNomeActionPerformed

    private void txfNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfNomeMouseClicked

        Estaticos.TEXTO = txfNome.getText();
        frmTeclado tecla = new frmTeclado(null, true);
        tecla.setVisible(true);
        txfNome.setText(Estaticos.TEXTO);
    }//GEN-LAST:event_txfNomeMouseClicked

    private void btnAnterior4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior4ActionPerformed
        tbpPrincipal.setSelectedIndex(3);
    }//GEN-LAST:event_btnAnterior4ActionPerformed

    private void btn5cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5cActionPerformed
        Estaticos.Questão5 = "a";
        resQuestão4 = Estaticos.Questão4;
        btn4a.setBackground(Color.GREEN);
        btn4b.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn5cActionPerformed

    private void btn5cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5cMouseClicked

    }//GEN-LAST:event_btn5cMouseClicked

    private void btn5bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5bActionPerformed
        Estaticos.Questão4 = "a";
        resQuestão4 = Estaticos.Questão4;
        btn4a.setBackground(Color.GREEN);
        btn4b.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);

    }//GEN-LAST:event_btn5bActionPerformed

    private void btn5bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5bMouseClicked

    }//GEN-LAST:event_btn5bMouseClicked

    private void btn5aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5aActionPerformed
        Estaticos.Questão4 = "a";
        resQuestão4 = Estaticos.Questão4;
        btn4a.setBackground(Color.GREEN);
        btn4b.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);

    }//GEN-LAST:event_btn5aActionPerformed

    private void btn5aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5aMouseClicked

    }//GEN-LAST:event_btn5aMouseClicked

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        Estaticos.MENSAGEM = "";

        resQuestão3 = Estaticos.Questão3;
        resQuestão4 = Estaticos.Questão4;
        resQuestão5 = Estaticos.Questão5;

        Controle controle = new Controle(txfNome.getText(), txfQuestao1.getText().toUpperCase(),
                txfQuestao2.getText().toUpperCase(), resQuestão3, resQuestão4, resQuestão5);

        if (Estaticos.MENSAGEM.equals(""))
        {
            String pontos = "";
            for (ArrayList<String> Visitante : Estaticos.DadosPessoas)
            {
                AnalisaDados analisadados = new AnalisaDados(null, null, null, null, null, null);
                pontos = Visitante.get(6);
                lblNomeVis.setText(Visitante.get(0));
                lblQ1Vis.setText(Visitante.get(1));
                lblQ2Vis.setText(Visitante.get(2));
                lblQ3Vis.setText(Visitante.get(3));
                lblQ4Vis.setText(Visitante.get(4));
                lblQ5Vis.setText(Visitante.get(5));

            }

            Integer IntPontos = Integer.valueOf(pontos);
            if (IntPontos >= 3)
            {
                lblParabens.setText("Parabens ");
                lblNomeParabens.setText(txfNome.getText());
                lblParabens2.setText("você conhece bem sobre a as expedições de marte");

            } else
            {
                lblParabens.setText("Sinto Muito");
                lblNomeParabens.setText(txfNome.getText());
                lblParabens2.setText("Você precisa aprender mais sobre marte");
            }

            tbpPrincipal.setSelectedIndex(5);

        } else
        {
            JOptionPane.showMessageDialog(null, Estaticos.MENSAGEM);
        }

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAnterior3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnterior3ActionPerformed
        tbpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_btnAnterior3ActionPerformed

    private void btn4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4aActionPerformed

    private void btn4aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4aMouseClicked
        Estaticos.Questão4 = "a";
        resQuestão4 = Estaticos.Questão4;
        btn4a.setBackground(Color.GREEN);
        btn4b.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);

    }//GEN-LAST:event_btn4aMouseClicked

    private void btn4bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4bActionPerformed

    private void btn4bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4bMouseClicked
        Estaticos.Questão4 = "b";
        resQuestão4 = Estaticos.Questão4;
        btn4b.setBackground(Color.GREEN);
        btn4a.setBackground(Color.WHITE);
        btn4c.setBackground(Color.WHITE);

    }//GEN-LAST:event_btn4bMouseClicked

    private void btn4cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4cActionPerformed

    private void btn4cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4cMouseClicked
        Estaticos.Questão4 = "c";
        resQuestão4 = Estaticos.Questão4;
        btn4c.setBackground(Color.GREEN);
        btn4a.setBackground(Color.WHITE);
        btn4b.setBackground(Color.WHITE);

    }//GEN-LAST:event_btn4cMouseClicked

    private void btnProximo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximo4ActionPerformed
        // TODO add your handling code here:
        tbpPrincipal.setSelectedIndex(4);
    }//GEN-LAST:event_btnProximo4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
        frmComecar frmC = new frmComecar(null, true);
        frmC.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgQuestao4;
    private javax.swing.ButtonGroup btgQuestao5;
    private javax.swing.JButton btn3a;
    private javax.swing.JButton btn3b;
    private javax.swing.JButton btn3c;
    private javax.swing.JButton btn4a;
    private javax.swing.JButton btn4b;
    private javax.swing.JButton btn4c;
    private javax.swing.JButton btn5a;
    private javax.swing.JButton btn5b;
    private javax.swing.JButton btn5c;
    private javax.swing.JButton btnAnterior1;
    private javax.swing.JButton btnAnterior2;
    private javax.swing.JButton btnAnterior3;
    private javax.swing.JButton btnAnterior4;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnProximo1;
    private javax.swing.JButton btnProximo2;
    private javax.swing.JButton btnProximo4;
    private javax.swing.JButton btnProximo6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl3a;
    private javax.swing.JLabel lbl3b;
    private javax.swing.JLabel lbl3c;
    private javax.swing.JLabel lbl4a;
    private javax.swing.JLabel lbl4b;
    private javax.swing.JLabel lbl4c;
    private javax.swing.JLabel lbl5a;
    private javax.swing.JLabel lbl5b;
    private javax.swing.JLabel lbl5c;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeParabens;
    private javax.swing.JLabel lblNomeVis;
    private javax.swing.JLabel lblParabens;
    private javax.swing.JLabel lblParabens2;
    private javax.swing.JLabel lblPontos;
    private javax.swing.JLabel lblPorcentagem;
    private javax.swing.JLabel lblQ1Vis;
    private javax.swing.JLabel lblQ2Vis;
    private javax.swing.JLabel lblQ3Vis;
    private javax.swing.JLabel lblQ4Vis;
    private javax.swing.JLabel lblQ5Vis;
    private javax.swing.JLabel lblQuestao1;
    private javax.swing.JLabel lblQuestao2;
    private javax.swing.JLabel lblQuestao4;
    private javax.swing.JLabel lblQuestao5;
    private javax.swing.JLabel lblQuestao6;
    private javax.swing.JLabel lblQuestão1nL;
    private javax.swing.JLabel lblQuestão4nL;
    private javax.swing.JLabel lblQustão5nL;
    private javax.swing.JLabel lblResNome;
    private javax.swing.JLabel lblResQ1;
    private javax.swing.JLabel lblResQ2;
    private javax.swing.JLabel lblResQ3;
    private javax.swing.JLabel lblResQ4;
    private javax.swing.JLabel lblResQ5;
    private javax.swing.JLabel lblRespondaSN;
    private javax.swing.JLabel lblRespondaSN2;
    private javax.swing.JLabel lblValorVisitante;
    private javax.swing.JPanel pnlQuestao1;
    private javax.swing.JPanel pnlQuestao2;
    private javax.swing.JPanel pnlQuestao3;
    private javax.swing.JPanel pnlQuestao4;
    private javax.swing.JPanel pnlQuestao5;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JTabbedPane tbpPrincipal;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfQuestao1;
    private javax.swing.JTextField txfQuestao2;
    // End of variables declaration//GEN-END:variables
}
